/**
 * CodeVault Data Configuration
 *
 * This file is auto-generated by `setup.mjs` which scans your codebase.
 * It defines the routes, API endpoints, database tables, and server actions
 * that CodeVault will manage.
 *
 * Structure:
 * - routes: Page routes in your application
 * - apiRoutes: API endpoints
 * - tables: Database tables
 * - serverActions: Server-side action files
 * - projectName: Name of your project
 * - framework: Framework type (e.g., "next.js", "sveltekit", "remix")
 */

window.CODEVAULT_DATA = {
  projectName: "My Project",
  framework: "generic",
  stagingUrl: "http://localhost:3000",     // Your dev/staging URL
  productionUrl: "",                       // Your production URL (leave empty if not deployed)

  // Pages/Routes
  routes: [
    // Example route:
    // {
    //   id: "home",
    //   name: "Homepage",
    //   path: "/",
    //   group: "public",
    //   type: "page",
    //   client: false,
    //   platform: "web",  // "web" | "ios" | "android" | "backend" | "shared"
    //   tables: []
    // },
  ],

  // API Routes/Endpoints
  apiRoutes: [
    // Example API route:
    // {
    //   id: "api-example",
    //   name: "Example API",
    //   path: "api/example",
    //   group: "api",
    //   type: "api",
    //   platform: "backend",  // "web" | "ios" | "android" | "backend" | "shared"
    //   tables: []
    // },
  ],

  // Database Tables
  tables: [
    // Example table:
    // {
    //   id: "t-users",
    //   name: "users",
    //   domain: "Core",
    //   platform: "shared",  // "web" | "ios" | "android" | "backend" | "shared"
    //   reads: 5,
    //   writes: 3
    // },
  ],

  // Server Actions / Backend Functions
  serverActions: [
    // Example server action:
    // {
    //   id: "sa-example",
    //   name: "example/actions.ts",
    //   path: "app/example",
    //   platform: "backend",  // "web" | "ios" | "android" | "backend" | "shared"
    //   lines: 1500,
    //   funcs: ["getExample", "createExample", "updateExample"],
    //   tables: ["examples"]
    // },
  ]
};
